version: "3.8"
services:
  app:
    build: .
    command: python main.py
    ports:
      - "8085:8085"
    volumes:
      - .:/docker-image
    environment:
      -  DARKSKY_API_KEY
      -  G_MAPS_API_KEY
